arch: ppc64le
os: linux-ppc64le

addons:
  apt:
    packages:
    - valgrind maven ant protobuf-compiler


jdk:
  - openjdk8

env:
  - MAVEN_OPTS=-Xmx2g MAVEN_SKIP_RC=true

cache:
  directories:
  - $HOME/.m2


script:
  - mkdir build
  - cd build
  - cmake -DANALYZE_JAVA=ON ..
  - make package test-out
  - cd ../java
  - mvn apache-rat:check
